### TODOS LOS AUTORES
GET http://localhost:3000/api/autores

### AUTORES BY ID
GET http://localhost:3000/api/autores/2



### Nuevo Usuario creado
POST http://localhost:3000/api/autores
Content-Type: application/json

{
    "nombre": "Fernando Pino",
    "email": "fpino@example.com",
    "imagen_url": "https://www.publicdomainpictures.net/pictures/40000/velka/young-man-portrait.jpg"
}


###POSTS GET ALL con datos del autor
GET http://localhost:3000/api/posts


### GET ID
GET http://localhost:3000/api/posts/5


### CREAR POST
POST http://localhost:3000/api/posts
Content-Type: application/json

{
  "titulo": "Impacto de la automatización en el empleo",
  "descripcion": "Un análisis sobre cómo la inteligencia artificial y la robótica están transformando el mercado laboral y qué sectores serán los más afectados en los próximos años.",
  "categoria": "noticias",
  "creado_en": "2024-06-18",
  "Autores_id": "5"
}