GET http://localhost:3000/api/autores

###
GET http://localhost:3000/api/autores/2
Content-Type: application/json


### Nuevo Usuario creado
POST http://localhost:3000/api/autores
Content-Type: application/json

{
    "nombre": "Fernando Robles",
    "email": "frob@example.com",
    "imagen_url": "https://www.publicdomainpictures.net/pictures/40000/velka/young-woman-portrait.jpg"
}


###POSTS
GET http://localhost:3000/api/posts/autores/3
Content-Type: application/json

### 
GET http://localhost:3000/api/posts/5
Content-Type: application/json

###
POST http://localhost:3000/api/posts
Content-Type: application/json